"""End-to-end pipeline: for every URL group in the DB, pick one anchor color,
run the expensive gpt-image-2 generation on the anchor only, then color-swap
the anchor's 6 views into every other color the URL offers. Builds review.html
when done.

Run `python app/batch.py` first to scrape and download the supplier images,
then `python app/pipeline.py` to generate + recolor + review."""

from __future__ import annotations

if __package__ in {None, ""}:
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import argparse
from collections import defaultdict
from typing import Any

from app.db import list_products
from app.generate import VIEW_SIZE, iter_jobs, run_jobs
from app.make_review_html import make_review_html
from app.paths import resolve_root_path
from app.prompts import ALL_VIEWS, VIEWS
from app.recolor import run_recolor, sample_target_color


# Anchor preference: chromatic, distant from skin tones AND from jeans (a
# common companion in Gildan model shots). 051 Royal Blue and 040 Red were
# both validated on G64000L. 194 Cherry Red and 098 Daisy are also strong.
# 032 Navy and 026 Sapphire are blue-family, share hue with jeans → less
# clean separation, but acceptable when nothing better is available.
# 036 Black / 030 White only appear at the tail — they're achromatic and
# can't anchor a Python recolor; products with only those colors get fully
# generated by gpt-image-2 instead.
ANCHOR_PREFERENCE = ["051", "040", "194", "098", "032", "026", "036", "030"]

# CustomInk color names that are achromatic — avoid as anchor when possible.
_ACHROMATIC_NAMES = {"BLACK", "WHITE", "NATURAL", "ASH", "HEATHER GREY", "SPORT GREY",
                     "LIGHT GREY", "DARK HEATHER", "CHARCOAL", "SILVER"}


def pick_anchor(group: list[dict[str, Any]]) -> dict[str, Any]:
    by_color = {(p.get("color") or "").upper(): p for p in group}
    # Gildan code preference list first
    for pref in ANCHOR_PREFERENCE:
        if pref in by_color:
            return by_color[pref]
    # For CustomInk (named colors): skip known achromatic names, prefer chromatic
    chromatic = [p for p in group if (p.get("color") or "").upper() not in _ACHROMATIC_NAMES]
    if chromatic:
        return chromatic[0]
    return group[0]


def group_by_url(products: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for p in products:
        groups[p["supplier_url"]].append(p)
    return groups


def estimate_cost(api_job_count: int) -> str:
    # Medium quality, mixed 1024x1536 (model views) + 1024x1024 (detail views).
    # 4 portrait + 2 square per anchor × ~$0.063 portrait, ~$0.042 square.
    per_set = 4 * 0.063 + 2 * 0.042
    sets = api_job_count / 6 if api_job_count else 0
    total = sets * per_set
    return f"~${total:.2f} ({int(sets)} set(s) × 6 views, mixed sizes)"


def anchor_is_chromatic(anchor: dict[str, Any]) -> bool:
    """A product can power Python recolor only if its supplier reference is
    a chromatic color — we need a defined hue to mask against."""
    ref = resolve_root_path(anchor.get("original_image_path"))
    if not ref or not ref.exists():
        return False
    try:
        return sample_target_color(ref).get("category") == "chromatic"
    except Exception:
        return False


def run_pipeline(
    quality: str | None = None,
    force: bool = False,
    ids: list[int] | None = None,
) -> dict[str, int]:
    products = list_products(statuses=["scraped"])
    if ids:
        id_set = set(ids)
        products = [p for p in products if p["id"] in id_set]
    if not products:
        raise SystemExit("No scraped products. Run `python app/batch.py` first.")

    groups = group_by_url(products)

    print(f"Pipeline: {len(products)} rows across {len(groups)} URL(s)\n")

    plans: list[tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]] = []
    for url, group in groups.items():
        anchor = pick_anchor(group)
        chromatic = anchor_is_chromatic(anchor)
        anchor_color = anchor.get("color") or "?"

        if chromatic:
            recolor_targets = [p for p in group if p["id"] != anchor["id"]]
            api_extras: list[dict[str, Any]] = []
        else:
            # No chromatic option — every color in the group must be generated.
            recolor_targets = []
            api_extras = [p for p in group if p["id"] != anchor["id"]]

        print(f"  {url}")
        print(
            f"    anchor #{anchor['id']:06d} color={anchor_color} "
            f"({'chromatic' if chromatic else 'achromatic'})"
        )
        if recolor_targets:
            tc = ", ".join(p.get("color") or "?" for p in recolor_targets)
            print(f"    recolor targets ({len(recolor_targets)}): {tc}")
        if api_extras:
            ec = ", ".join(p.get("color") or "?" for p in api_extras)
            print(f"    extra gpt-image-2 (no chromatic anchor available) ({len(api_extras)}): {ec}")
        plans.append((anchor, recolor_targets, api_extras))

    # Phase 1 — gpt-image-2 generation on anchors + any forced-API extras
    api_jobs = []
    for anchor, _, api_extras in plans:
        api_jobs.extend(iter_jobs([anchor], [v["key"] for v in ALL_VIEWS], force=force))
        if api_extras:
            api_jobs.extend(iter_jobs(api_extras, [v["key"] for v in ALL_VIEWS], force=force))

    if api_jobs:
        print(f"\nPhase 1: gpt-image-2 generation — {len(api_jobs)} image(s), {estimate_cost(len(api_jobs))}")
        counts = run_jobs(api_jobs, quality=quality)
        print(f"  gpt-image-2: ok={counts['ok']} fail={counts['fail']}")
    else:
        print("\nPhase 1: skipped — every needed view is already on disk.")
        counts = {"ok": 0, "fail": 0}

    # Phase 2 — Python recolor anchor → every recolor target in the group
    recolor_counts = {"ok": 0, "skip": 0, "fail": 0}
    print("\nPhase 2: Python recolor")
    for anchor, recolor_targets, _ in plans:
        if not recolor_targets:
            continue
        target_ids = [p["id"] for p in recolor_targets]
        try:
            c = run_recolor(anchor_id=anchor["id"], target_ids=target_ids, force=force)
            for key in recolor_counts:
                recolor_counts[key] += c.get(key, 0)
        except SystemExit as exc:
            print(f"  skip group: {exc}")

    # Phase 3 — review.html
    print("\nPhase 3: build review HTML")
    html_path = make_review_html()
    print(f"  -> {html_path}")

    return {
        "groups": len(groups),
        "api_ok": counts["ok"],
        "api_fail": counts["fail"],
        "recolor_ok": recolor_counts["ok"],
        "recolor_fail": recolor_counts["fail"],
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="One-shot batch: gpt-image-2 anchor generation + Python recolor "
        "for every URL group in the DB."
    )
    parser.add_argument(
        "--quality",
        choices=["low", "medium", "high", "auto"],
        help="Override OPENAI_IMAGE_QUALITY (default: medium)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-generate anchors and re-recolor targets even if files exist",
    )
    parser.add_argument(
        "--ids",
        help="Comma-separated product IDs to process (e.g. 113,114). Skips all others.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    ids = [int(x.strip()) for x in args.ids.split(",")] if args.ids else None
    result = run_pipeline(quality=args.quality, force=args.force, ids=ids)
    print(
        f"\nDone. groups={result['groups']} "
        f"anchor_generated={result['api_ok']} anchor_failed={result['api_fail']} "
        f"recolored={result['recolor_ok']} recolor_failed={result['recolor_fail']}\n"
        "Open review.html to see the gallery."
    )


if __name__ == "__main__":
    main()
