export interface ProductColor {
    name: string;
    hex: string;
    availableSizes: string[];
    isAvailable: boolean;
}

export const PRODUCT_COLORS: ProductColor[] = [
    { name: 'White', hex: '#ffffff', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Navy', hex: '#1c203b', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Maroon', hex: '#731f39', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Black', hex: '#000000', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sport Grey', hex: '#afafaf', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Dark Grey', hex: '#545454', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Red', hex: '#f40928', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Royal Blue', hex: '#395389', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Forest Green', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Purple', hex: '#4f237a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Pink', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Orange', hex: '#dc582a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Yellow', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Charcoal', hex: '#494949', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Blue', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Red', hex: '#a54d58', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Light Blue', hex: '#afcdf3', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Kelly Green', hex: '#33755a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Lime', hex: '#86b660', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Gold', hex: '#e79628', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Silver', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Brown', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Tan', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Olive', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Teal', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Burgundy', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Dark Heather', hex: '#4d4d4d', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Light Pink', hex: '#e6c7da', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Hot Pink', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Coral', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Peach', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Lavender', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Mint', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Turquoise', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sky Blue', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Navy Blue', hex: '#1c203b', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Royal', hex: '#395389', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Carolina Blue', hex: '#92b0e6', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sapphire', hex: '#0387b8', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Steel Blue', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Slate', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Steel', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Graphite Heather', hex: '#7f7f7f', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Charcoal Heather', hex: '#4a4a4a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Ash', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Natural', hex: '#e9e3cb', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sand', hex: '#d1c8b7', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cream', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Ivory', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Light Grey', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Grey', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Dark Grey', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Gunmetal', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Midnight', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Indigo', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Plum', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Wine', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cranberry', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cardinal', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Scarlet', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cherry Red', hex: '#d2023e', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Orange Red', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Orange', hex: '#ff6600', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Green', hex: '#ccff33', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Yellow', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Pink', hex: '#ff33cc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Blue', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Purple', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Lime', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Aqua', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Brown', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Tan', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Navy', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Black', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety White', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Safety Grey', hex: '#cccccc', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
];

