export interface ProductColor {
    name: string;
    hex: string;
    availableSizes: string[];
    isAvailable: boolean;
}

export const PRODUCT_COLORS: ProductColor[] = [
    { name: 'White', hex: '#ffffff', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Ice Grey', hex: '#b7b7b9', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sport Grey', hex: '#afafaf', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Graphite Heather', hex: '#7f7f7f', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Dark Grey', hex: '#545454', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Dark Heather', hex: '#4d4d4d', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Charcoal', hex: '#494949', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Black', hex: '#000000', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Navy', hex: '#1c203b', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Navy', hex: '#4c5064', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Indigo', hex: '#738a9a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Stone Blue', hex: '#8a9ead', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Metro Blue', hex: '#3b4165', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Royal', hex: '#395389', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Iris', hex: '#6588c8', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Royal', hex: '#4d68a3', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Antique Sapphire', hex: '#007d9e', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sapphire', hex: '#0387b8', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Carolina Blue', hex: '#92b0e6', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Sapphire', hex: '#5790b4', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Jade Dome', hex: '#008b80', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Tropical Blue', hex: '#219099', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Galapagos Blue', hex: '#68969d', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Light Blue', hex: '#afcdf3', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sky', hex: '#96d2e6', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Indigo Blue', hex: '#626c79', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Purple', hex: '#60558f', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Purple', hex: '#4f237a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Cardinal Red', hex: '#a04759', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Maroon', hex: '#731f39', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Maroon', hex: '#654751', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cardinal Red', hex: '#922238', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Red', hex: '#f40928', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Red', hex: '#a54d58', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cherry Red', hex: '#d2023e', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Antique Cherry Red', hex: '#811e36', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Berry', hex: '#b1567c', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Antique Heliconia', hex: '#943962', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Heliconia', hex: '#be5269', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Azalea', hex: '#e274a5', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Radiant Orchid', hex: '#ad6c8f', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Light Pink', hex: '#e6c7da', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Orange', hex: '#dc582a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Orange', hex: '#e77466', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Coral Silk', hex: '#e76e68', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Cornsilk', hex: '#f1e189', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Daisy', hex: '#ecd45a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Gold', hex: '#e79628', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Military Green', hex: '#5f6a50', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Military Green', hex: '#74746d', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Mint Green', hex: '#c8eec1', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Kiwi', hex: '#85a35b', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Lime', hex: '#86b660', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Irish Green', hex: '#3ba658', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Heather Irish Green', hex: '#5fa66d', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Kelly Green', hex: '#33755a', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sand', hex: '#d1c8b7', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Natural', hex: '#e9e3cb', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Dark Chocolate', hex: '#413829', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Sage', hex: '#a7ada3', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Off White', hex: '#f2ead5', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Paragon', hex: '#9f8b95', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
    { name: 'Pistachio', hex: '#bed8a3', availableSizes: ["S", "M", "L", "XL", "2XL"], isAvailable: true },
];

